version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:80"

  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
