version: '3.8'
services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"

  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=public
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
